// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1k7AXR3wcWF_uyBA4uKR8pl_OczYYtk8',
    appId: '1:988379877914:web:944ccf6cc4b830cca437a3',
    messagingSenderId: '988379877914',
    projectId: 'app001-9fa22',
    authDomain: 'app001-9fa22.firebaseapp.com',
    storageBucket: 'app001-9fa22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNl7umVIrhD_b3ITm9tNCyjPmQkIawIc',
    appId: '1:988379877914:android:c7e1c9cf6bb366a6a437a3',
    messagingSenderId: '988379877914',
    projectId: 'app001-9fa22',
    storageBucket: 'app001-9fa22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGO3Q2Rho2HpYeu-LlBfSC5YhxnM8kRJY',
    appId: '1:988379877914:ios:647a39b578120fefa437a3',
    messagingSenderId: '988379877914',
    projectId: 'app001-9fa22',
    storageBucket: 'app001-9fa22.appspot.com',
    iosClientId: '988379877914-pigve5u9jfe5ad2o08v7vj7g9agth3op.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGO3Q2Rho2HpYeu-LlBfSC5YhxnM8kRJY',
    appId: '1:988379877914:ios:647a39b578120fefa437a3',
    messagingSenderId: '988379877914',
    projectId: 'app001-9fa22',
    storageBucket: 'app001-9fa22.appspot.com',
    iosClientId: '988379877914-pigve5u9jfe5ad2o08v7vj7g9agth3op.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
